# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: REACT_HOOK_FORM_CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2  
      with:
       version: 6.32.9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm run test

  build:
    name: Build react-hook-from-app
    runs-on: ubuntu-latest
    needs: run_tests # this job must be run after the run_tests job successfully completes
    strategy:
      matrix:
        node-version: [ 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2  
      with:
       version: 6.32.9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm run test
  publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: build # this job must be run after the build job successfully completes
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2  
        with:
         version: 6.32.9
      - name: publish docker image to docker hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/react-hook-form-app:latest
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}